### ISSUE TITLE
Agora Bank v1

### ISSUE THREAD

**Issue by Brunya** [AgoraSpaceDAO/agora-contracts#8]
![Screenshot 2021-05-26 at 15 00 16](https://user-images.githubusercontent.com/32143596/119663884-16334380-be33-11eb-8d10-47bce2340ef2.png)

Simplified tokenomics for Agora Bank v1.
The previous one had weaknesses. The concept is getting cleaner.

### Staking mechanism
- We are tracking community IDs on off-chain (on HUB server) 
- Owners stake their first amount of AGO into a specific ID when they created a community
- Supporter Members can stake AGO into a specific community-pool with ID
- When someone stakes AGO it is locked for 3 months
- When someone stakes again into the same community-pool the timelock resets
- When someone withdraws AGO the timelock doesn't reset

### Minting mechanism
- Rewards stakers
- Inflation percent adjustable by governance (0-100% / year)
- Minting is proportional to all staked AGO
- The frequency of minting is per block

### The functions roughly:
**Write functions**
- stake(amount, address, communityId, block) + Event
- withdraw(amount, communityId) + Event
- claimReward()
- changeInflationPercent(percent) + Event
- changeTimelockPeriod()
- setNewGovernanceWallet(wallet) + Event

**Read functions**
- getAllStakes()
- getUserBalance(address, communityId)
- getCommunityBalance(communityId)
- getRewardAmount()
- getInflationPercent()
- getGovernanceWallet()

Function names can be renamed.

Open question:
Should we work with blockstamps or timestamps?

(I still owe you the return values and actions)

**Comment by Brunya** [comment]
We should determine the minting based on blocks.
This means the inflation should be calculate in AGO per block, instead of the annual percent

This parameter is 0.1 AGO / block in the first case.
Stakers (owners and supporters) benefit proportionately from the minting.

**Comment by TomiOhl** [comment]
**First implementation of Agora Bank and AGO token deployed to ropsten:**

- Agora Bank: [0x3797daD8d9B2e6545d55F4e79Dd380A245A03db4](https://ropsten.etherscan.io/address/0x3797daD8d9B2e6545d55F4e79Dd380A245A03db4)
- AGO token: [0x6d9f2611DB3c5107c48AE13895f65Ae570bf024B](https://ropsten.etherscan.io/token/0x6d9f2611DB3c5107c48AE13895f65Ae570bf024B)

**Functions/events in this implementation compared to the ones in the first comment:**

| Issue                                      | Implementation                                                                |
| ------------------------------------------ | ----------------------------------------------------------------------------- |
| stake(amount, address, communityId, block) | deposit(uint256 \_communityId, uint256 \_amount)                              |
| stake Event                                | Deposit(uint256 indexed communityId, address indexed wallet, uint256 amount)  |
| withdraw(amount, communityId)              | withdraw(uint256 \_communityId, uint256 \_amount)                             |
| withdraw Event                             | Withdraw(uint256 indexed communityId, address indexed wallet, uint256 amount) |
| claimReward()                              | claimReward(uint256[] memory \_communityIds)                                  |
| -                                          | event RewardClaimed(uint256[] communityIds, address indexed wallet)           |
| changeInflationPercent(percent)            | changeRewardPerBlock(uint256 \_rewardAmount)                                  |
| changeInflationPercent Event               | RewardChanged(uint256 newRewardPerBlock)                                      |
| changeTimelockPeriod()                     | changeTimelockInterval(uint256 \_blocks)                                      |
| setNewGovernanceWallet(wallet)             | transferOwnership(address newOwner)                                           |
| setNewGovernanceWallet Event               | OwnershipTransferred(address indexed previousOwner, address indexed newOwner) |
| getAllStakes()                             | totalStakes()                                                                 |
| getUserBalance(address, communityId)       | get it from _stakes_ mapping                                                  |
| getCommunityBalance(communityId)           | needs to be calculated off-chain                                              |
| getRewardAmount()                          | getReward(uint256[] calldata \_communityIds)                                  |
| getInflationPercent()                      | rewardPerBlock()                                                              |
| getGovernanceWallet()                      | owner()                                                                       |
| -                                          | lockInterval()                                                                |
| -                                          | agoAddress()                                                                  |

**Note:**

- the reward amount might be too high, especially with default settings.
- initial supply for AGO is minted in the constructor to the deployer.
- the governance is not able to mint tokens but can grant anyone the role required for minting. Additional steps should be considered to make sure the governance grants that role only to the Agora Bank contract and any future versions of it.
